# Generated by Django 2.1.3 on 2019-02-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190208_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='contact_no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
