# Generated by Django 2.1.3 on 2018-12-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('recevier', models.CharField(max_length=50)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('patient_email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
                ('submitted_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='diseases',
            fields=[
                ('diseases_id', models.IntegerField(primary_key=True, serialize=False)),
                ('diseases_name', models.CharField(max_length=50)),
                ('diseases_type', models.CharField(max_length=50)),
                ('diseases_syptom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('doctor_status', models.IntegerField(default=0)),
                ('doctor_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='genric_medicines',
            fields=[
                ('medicine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine_pricicription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='nongenric_medicines',
            fields=[
                ('medicine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine_pricicription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='patients_register',
            fields=[
                ('Id', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Date_of_birth', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=100)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('patient_status', models.IntegerField(default=0)),
                ('patient_Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
