# Generated by Django 2.1.3 on 2018-12-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genric_medicines',
            old_name='medicine_pricicription',
            new_name='medicine_prescription',
        ),
        migrations.RenameField(
            model_name='nongenric_medicines',
            old_name='medicine_pricicription',
            new_name='medicine_prescription',
        ),
    ]
